###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: gao-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=gao
        - POSTGRES_PASSWORD=gao
        - POSTGRES_DB=gao
      ports:
        - "1034:5432"

    webserver:
      image: nginx:alpine
      container_name: gao-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1030:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: gao-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

